# center right

waypoints = [
  {x = 0.0, y = 0.0, angle = 0.0},
#  {x = 1.4, y = -0.8, angle = -35.0},
  {x = 2.45, y = -1.38, angle = 0.0},
]

fit              = "HERMITE_CUBIC"
sample_count     = 20_000
dt               = 0.05  # sec
max_velocity     = 3.0   # m/sec
max_acceleration = 4.5   # m/sec/sec
max_jerk         = 20.0  # m/sec/sec/sec
