waypoints = [
  {x = 0.0, y = 0.0, angle = -35.0},
  {x = 7.5, y = -3.7, angle = 0.0},
  {x = 6.0, y = -2.5, angle = -90.0},
  {x = 6.0, y = -1.0, angle = -90.0},
  {x = 5.0, y = -1.7, angle = -180.0},
  {x = 0.0, y = 1.5, angle = -180.0}

]

fit              = "HERMITE_CUBIC"
sample_count     = 100_000
dt               = 0.05  # sec
max_velocity     = 1.7   # m/sec
max_acceleration = 2.0   # m/sec/sec
max_jerk         = 60.0  # m/sec/sec/sec
