waypoints = [
  {x = 0.0, y = 0.0, angle = 35.0},
  {x = 1.4, y = 1.0, angle = 40.0},
  {x = 2.65, y = 1.7, angle = 0.0},
]

fit              = "HERMITE_CUBIC"
sample_count     = 100_000
dt               = 0.05  # sec
max_velocity     = 2.0   # m/sec
max_acceleration = 1.5   # m/sec/sec
max_jerk         = 10.0  # m/sec/sec/sec
