waypoints = [
  {x = 0.0, y = 0.0, angle = 0.0},
  {x = 15.8, y = 0.0, angle = 0.0},
  {x = 17.8, y = 2.0, angle = -90.0},
  {x = 17.8, y = 16.0, angle = -90.0},
]
fit              = "HERMITE_CUBIC"
sample_count     = 100_000
dt               = 0.050    # sec
max_velocity     = 5.0   # m/sec
max_acceleration = 2.0  # m/sec/sec
max_jerk         = 60.0  # m/sec/sec/sec