# left opposite scale

waypoints = [
  {x = 0.0, y = 0.0, angle = 0.0},
  {x = 2.0, y = 0.50, angle = 0.0},
  {x = 3.4, y = 0.50, angle = 0.0},
  {x = 5.38, y = -1.2, angle = -90.0},
  {x = 5.38, y = -4.15, angle = -90.0},
  {x = 6.5, y = -5.45, angle = 0.0},
]

fit              = "HERMITE_CUBIC"
sample_count     = 20_000
dt               = 0.050    # sec
max_velocity     = 3.0   # m/sec
max_acceleration = 2.5  # m/sec/sec
max_jerk         = 60.0  # m/sec/sec/sec