# left opposite scale with delay

waypoints = [
  {x = 0.0, y = 0.0, angle = -45.0},
  {x = 0.15, y = -0.6, angle = -90.0},
  {x = 0.15, y = -2.5, angle = -90.0},
  {x = 0.15, y = -4.7, angle = -90.0},
  {x = 2.30, y = -6.7, angle = 0.0},
  {x = 3.50, y = -6.7, angle = 0.0},
]

fit              = "HERMITE_CUBIC"
sample_count     = 20_000
dt               = 0.050    # sec
max_velocity     = 3.5   # m/sec
max_acceleration = 3.5  # m/sec/sec
max_jerk         = 60.0  # m/sec/sec/sec