# left opposite scale

waypoints = [
  {x = 0.0, y = 0.0, angle = 0.0},
  {x = 2.3, y = 0.50, angle = 0.0},
  {x = 3.90, y = 0.50, angle = 0.0},
  {x = 5.85, y = -1.7, angle = -90.0},
  {x = 5.85, y = -3.85, angle = -90.0},
]

fit              = "HERMITE_CUBIC"
sample_count     = 20_000
dt               = 0.050    # sec
max_velocity     = 3.5   # m/sec
max_acceleration = 3.5  # m/sec/sec
max_jerk         = 60.0  # m/sec/sec/sec