waypoints = [
  {x = 0.0, y = 0.0, angle = 0.0},
  {x = 8.0, y = -0.2, angle = 0.0},
  {x = 10.0, y = -0.4, angle = 0.0},
  {x = 11.5, y = -0.7, angle = 0.0},
  {x = 12.0, y = -1.5, angle = -90.0},
]

fit              = "HERMITE_CUBIC"
sample_count     = 100_000
dt               = 0.05  # sec
max_velocity     = 1.7   # m/sec
max_acceleration = 2.0   # m/sec/sec
max_jerk         = 60.0  # m/sec/sec/sec
p_azimuth        = -0.004
