waypoints = [
  {x = 0.0, y = 0.0, angle = 0.0},
  {x = 3.861, y = -0.65, angle = 0.0},
]
fit              = "HERMITE_CUBIC"
sample_count     = 10_000
dt               = 0.050    # sec
max_velocity     = 2.0   # m/sec
max_acceleration = 1.5  # m/sec/sec
max_jerk         = 60.0  # m/sec/sec/sec