# right opposite switch

waypoints = [
  {x = 0.0, y = 0.0, angle = 0.0},
  {x = 4.8, y = 0.0, angle = 0.0},
  {x = 5.7, y = 1.2, angle = 90.0},
  {x = 5.7, y = 4.10, angle = 90.0},
]

fit              = "HERMITE_CUBIC"
sample_count     = 20_000
dt               = 0.050    # sec
max_velocity     = 3.5   # m/sec
max_acceleration = 3.5  # m/sec/sec
max_jerk         = 20.0  # m/sec/sec/sec