# right opposite switch

waypoints = [
  {x = 0.0, y = 0.0, angle = 0.0},
  {x = 4.6, y = 0.0, angle = 0.0},
  {x = 5.5, y = 1.2, angle = 90.0},
  {x = 5.5, y = 3.85, angle = 90.0},
]

fit              = "HERMITE_CUBIC"
sample_count     = 20_000
dt               = 0.050    # sec
max_velocity     = 1.5   # m/sec
max_acceleration = 1.5  # m/sec/sec
max_jerk         = 60.0  # m/sec/sec/sec