waypoints = [
  {x = 0.0, y = 0.0, angle = 0.0},
  {x = 2.20, y = -1.50, angle = 0.0},
]

fit              = "HERMITE_CUBIC"
sample_count     = 20_000
dt               = 0.050    # sec
max_velocity     = 1.5   # m/sec
max_acceleration = 1.5  # m/sec/sec
max_jerk         = 20.0  # m/sec/sec/sec