waypoints = [
  {x = 0.0, y = 0.0, angle = 0.0},
  {x = 2.5, y = 0.0, angle = 0.0},
]

fit              = "HERMITE_CUBIC"
sample_count     = 100_000
dt               = 0.05  # sec
max_velocity     = 1.0   # m/sec
max_acceleration = 1.0   # m/sec/sec
max_jerk         = 60.0  # m/sec/sec/sec
